drpg-example-001/example001:
  url: "/example001"
  policy: "drpg-example-001/example001"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
  wssProcessingEnabled: false
jupiter/HelloWorld:
  url: "/helloworld"
  policy: "jupiter/HelloWorld"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
  wssProcessingEnabled: false
jupiter/Info:
  url: "/info*"
  policy: "jupiter/Info"
  httpMethods:
  - "OTHER"
  - "HEAD"
  - "DELETE"
  - "POST"
  - "GET"
  - "OPTIONS"
  - "PUT"
  - "PATCH"
  properties: {}
  wssProcessingEnabled: false
